(() => {
  const storeKey="momentAccessControlV1",pages=[["dashboard.html","Dashboard"],["clock-in-out.html","Clock In/Out"],["schedule.html","Schedule"],["my-hours.html","My Hours"],["job-calendar.html","Calendar"],["lab-work.html","Lab Pipeline"],["lab-manual.html","Lab Manual"],["correspondence.html","Correspondence"],["documents.html","Documents"],["index.html","Boring Logs"],["lab-inventory.html","Custody"],["payroll.html","Payroll"],["contacts.html","Contacts"],["me.html","Me"],["reports.html","Reports"]],divisions=["Civil Engineering","Geotechnical"];
  const read=()=>{try{const value=JSON.parse(localStorage.getItem(storeKey)||"{}");return{ownerHash:value.ownerHash||"",ownerCode:value.ownerCode||"",workers:Array.isArray(value.workers)?value.workers:[]}}catch{return{ownerHash:"",ownerCode:"",workers:[]}}};
  let data=read();
  const save=()=>localStorage.setItem(storeKey,JSON.stringify(data));
  const hash=async value=>{const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return[...new Uint8Array(digest)].map(byte=>byte.toString(16).padStart(2,"0")).join("")};
  const safe=value=>String(value??"").replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[char]);
  const permissionOptions=(selected=[],name="permission")=>pages.map(([href,label])=>`<label class="permission-option"><input type="checkbox" name="${name}" value="${href}" ${selected.includes(href)?"checked":""}>${label}</label>`).join("");
  const pills=(values,all,name,type)=>all.map(value=>`<label class="access-pill"><input type="checkbox" name="${name}" value="${value}" ${values.includes(value)?"checked":""}>${type==="page"?(pages.find(page=>page[0]===value)?.[1]||value):value}</label>`).join("");
  function normalize(worker){worker.role||="employee";worker.title||="Worker";worker.email||="";worker.phone||="";worker.color||="#2f6f58";worker.divisions=Array.isArray(worker.divisions)?worker.divisions:["Geotechnical"];worker.permissions=Array.isArray(worker.permissions)?worker.permissions:[];return worker}
  function render(){
    data.workers.forEach(normalize);
    document.querySelector("#workerCount").textContent=`${data.workers.length} team member${data.workers.length===1?"":"s"}`;
    document.querySelector("#workerList").innerHTML=data.workers.length?data.workers.map(worker=>`<article class="person-row" data-worker="${safe(worker.id)}"><div class="person-identity"><strong>${safe(worker.name)}</strong><span>${safe(worker.title)}</span><div class="person-contact"><input type="email" data-email value="${safe(worker.email)}" placeholder="Email" aria-label="Email for ${safe(worker.name)}"><input type="tel" data-phone value="${safe(worker.phone)}" placeholder="Phone" aria-label="Phone for ${safe(worker.name)}"><input type="color" data-color value="${safe(worker.color)}" aria-label="Schedule color for ${safe(worker.name)}"></div><label><input type="checkbox" data-active ${worker.active!==false?"checked":""}> Active account</label></div><div class="row-role"><select class="role-select" data-role aria-label="Role for ${safe(worker.name)}"><option value="employee" ${worker.role==="employee"?"selected":""}>Employee</option><option value="manager" ${worker.role==="manager"?"selected":""}>Manager</option><option value="admin" ${worker.role==="admin"?"selected":""}>Admin</option></select></div><div class="row-divisions">${pills(worker.divisions,divisions,`division-${worker.id}`,"division")}</div><div class="row-permissions">${pills(worker.permissions,pages.map(page=>page[0]),`permission-${worker.id}`,"page")}</div><div class="code-cell"><input type="text" minlength="4" value="${safe(worker.code||"")}" placeholder="Set new code" data-code aria-label="Login code for ${safe(worker.name)}"><button type="button" data-save-code>Save</button></div><div class="row-actions"><button type="button" data-delete>Remove</button></div></article>`).join(""):'<div class="empty-workers">No team members yet. Select “Add person” to create the first profile.</div>';
  }
  function currentWorker(target){const row=target.closest("[data-worker]");return{row,worker:data.workers.find(item=>item.id===row?.dataset.worker)}}
  document.addEventListener("DOMContentLoaded",()=>{
    const ownerInput=document.querySelector("#ownerCode"),panel=document.querySelector("#addWorkerPanel");
    ownerInput.value=data.ownerCode;document.querySelector("#ownerStatus").textContent=data.ownerCode?`Current code: ${data.ownerCode}`:data.ownerHash?"Set a new code to display it":"No admin code set";document.querySelector("#newWorkerPermissions").innerHTML=permissionOptions(pages.map(page=>page[0]));
    document.querySelector("#showWorkerForm").addEventListener("click",()=>panel.hidden=false);document.querySelector("#closeWorkerForm").addEventListener("click",()=>panel.hidden=true);
    document.querySelector("#ownerCodeForm").addEventListener("submit",async event=>{event.preventDefault();const code=ownerInput.value.trim();data.ownerCode=code;data.ownerHash=await hash(code);save();document.querySelector("#ownerStatus").textContent=`Current code: ${code}`});
    document.querySelector("#workerForm").addEventListener("submit",async event=>{event.preventDefault();const name=document.querySelector("#workerName").value.trim(),code=document.querySelector("#workerCode").value.trim(),title=document.querySelector("#workerTitle").value.trim()||"Worker",email=document.querySelector("#workerEmail").value.trim(),phone=document.querySelector("#workerPhone").value.trim(),color=document.querySelector("#workerColor").value,role=document.querySelector("#workerRole").value,workerDivisions=[...document.querySelectorAll('[name="newDivision"]:checked')].map(input=>input.value),permissions=[...document.querySelectorAll('[name="permission"]:checked')].map(input=>input.value);data.workers.push({id:crypto.randomUUID?.()||String(Date.now()),name,title,email,phone,color,role,divisions:workerDivisions,active:true,code,codeHash:await hash(code),permissions});save();event.target.reset();document.querySelector("#workerColor").value="#2f6f58";document.querySelector("#newWorkerPermissions").innerHTML=permissionOptions(pages.map(page=>page[0]));panel.hidden=true;render()});
    document.querySelector("#workerList").addEventListener("change",event=>{const{row,worker}=currentWorker(event.target);if(!worker)return;if(event.target.matches("[data-active]"))worker.active=event.target.checked;else if(event.target.matches("[data-role]"))worker.role=event.target.value;else if(event.target.matches("[data-email]"))worker.email=event.target.value.trim();else if(event.target.matches("[data-phone]"))worker.phone=event.target.value.trim();else if(event.target.matches("[data-color]"))worker.color=event.target.value;else if(event.target.closest(".row-divisions"))worker.divisions=[...row.querySelectorAll('.row-divisions input:checked')].map(input=>input.value);else if(event.target.closest(".row-permissions"))worker.permissions=[...row.querySelectorAll('.row-permissions input:checked')].map(input=>input.value);save()});
    document.querySelector("#workerList").addEventListener("click",async event=>{const{row,worker}=currentWorker(event.target);if(!worker)return;if(event.target.matches("[data-delete]")){if(!confirm(`Remove ${worker.name}'s profile?`))return;data.workers=data.workers.filter(item=>item.id!==worker.id);save();render();return}if(event.target.matches("[data-save-code]")){const input=row.querySelector("[data-code]"),code=input.value.trim();if(code.length<4){input.focus();return}worker.code=code;worker.codeHash=await hash(code);save();event.target.textContent="Saved";setTimeout(()=>event.target.textContent="Save",1000)}});
    render();
  });
})();
document.addEventListener("DOMContentLoaded",()=>{const email=document.querySelector("#adminAccountEmail");if(email)email.textContent=localStorage.getItem("boringLogCurrentUser")||"Not connected"});
