(() => {
  const stateKey="boringLogAppState", calendarKey="moment-job-calendar-v1", proposalKey="moment-proposals-v1";
  const $=selector=>document.querySelector(selector), money=value=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(Number(value)||0);
  const esc=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[char]));
  const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;
  const placeholderImage=label=>`data:image/svg+xml;charset=utf-8,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="600" height="360"><rect width="100%" height="100%" fill="#f1f3f0"/><text x="50%" y="50%" text-anchor="middle" dominant-baseline="middle" font-family="Arial" font-size="24" fill="#858b86">${label}</text></svg>`)}`;
  const placeholderImages={property:placeholderImage("Property photo"),hazard:placeholderImage("Hazard map"),sitePlan:placeholderImage("Site plan")};
  let allProjects=[], eligible=[], proposals={}, selectedId="", saveTimer=0;
  const defaults=()=>({client:"",jobNumber:"",address:"",proposalDate:new Date().toISOString().slice(0,10),preparedBy:"Moment Engineering",scope:"Geotechnical investigation for the proposed improvements at the subject property.",images:{property:"",hazard:"",sitePlan:""},overhead:25,markup:15,retainer:50,notes:["Work will be performed in accordance with the scope described above.","Work outside this scope will be proposed separately.","Rates are billed hourly except where noted as a flat rate."].join("\n"),lines:[{id:uid(),description:"Geotechnical Engineer (PE) - analysis and report",hours:10,rate:150},{id:uid(),description:"Field Technician - site investigation",hours:8,rate:80},{id:uid(),description:"Laboratory Technician - testing",hours:8,rate:80},{id:uid(),description:"Contingency",hours:"",rate:480,flat:true}]});
  function read(key,fallback){try{return JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback))}catch{return fallback}}
  function load(){const state=read(stateKey,{}),jobs=read(calendarKey,[]),borings=Array.isArray(state.borings)?state.borings:[];allProjects=Array.isArray(state.projects)?state.projects:[];const scheduled=new Set((Array.isArray(jobs)?jobs:[]).map(job=>job.sourceProjectId).filter(Boolean));eligible=allProjects.filter(project=>!scheduled.has(project.id)&&!borings.some(boring=>boring.projectId===project.id&&(boring.samples||[]).length));proposals=read(proposalKey,{});renderProjectOptions();}
  function projectLabel(project){return [project.number,project.name||project.address,project.client].filter(Boolean).join(" · ")||"Untitled project"}
  function renderProjectOptions(){const select=$("#projectSelect");select.innerHTML=eligible.length?eligible.map(project=>`<option value="${esc(project.id)}">${esc(projectLabel(project))}</option>`).join(""):`<option value="">No eligible projects</option>`;select.disabled=!eligible.length;$("#downloadPdf").disabled=!eligible.length;selectedId=eligible[0]?.id||"";$("#projectHelp").textContent=eligible.length?`${eligible.length} eligible project${eligible.length===1?"":"s"}`:"Every saved project is scheduled or already has samples.";if(selectedId)showProject(selectedId);else renderEmpty();}
  function current(){return proposals[selectedId]}
  function showProject(id){selectedId=id;const project=eligible.find(item=>item.id===id);if(!project)return;const saved=proposals[id]||defaults();proposals[id]={...saved,images:{property:"",hazard:"",sitePlan:"",...(saved.images||{})},projectId:id,client:saved.client||project.client||project.name||"",jobNumber:saved.jobNumber||project.number||"",address:saved.address||project.address||""};const p=current();["client","jobNumber","address","proposalDate","preparedBy","scope","overhead","markup","retainer","notes"].forEach(key=>$("#"+key).value=p[key]??"");renderLines();renderImageUploads();renderPreview();}
  function renderImageUploads(){const images=current()?.images||{};document.querySelectorAll("[data-image-slot]").forEach(card=>{const key=card.dataset.imageSlot,value=images[key]||"",preview=card.querySelector(".image-upload-preview"),remove=card.querySelector("[data-remove-image]");preview.innerHTML=value?`<img src="${value}" alt="${esc(key)} preview">`:`<span>No image</span>`;remove.disabled=!value})}
  function renderLines(){const p=current();$("#lineItems").innerHTML=p.lines.map((line,index)=>`<div class="line-item" data-index="${index}"><label>Description<input data-key="description" value="${esc(line.description)}"></label><label>Hours<input data-key="hours" type="number" min="0" step=".25" value="${esc(line.hours)}"></label><label>${line.flat?"Flat fee":"Rate"}<input data-key="rate" type="number" min="0" step="1" value="${esc(line.rate)}"></label><button class="remove-line" data-remove="${index}" type="button" aria-label="Remove service">×</button></div>`).join("");}
  function calculate(p){const rows=p.lines.map(line=>({...line,fee:line.flat?Number(line.rate)||0:(Number(line.hours)||0)*(Number(line.rate)||0)})),base=rows.reduce((sum,row)=>sum+row.fee,0),hourly=rows.filter(row=>!row.flat).reduce((sum,row)=>sum+row.fee,0),subconsultant=rows.filter(row=>/geolog|subconsult/i.test(row.description)).reduce((sum,row)=>sum+row.fee,0),overhead=hourly*(Number(p.overhead)||0)/100,markup=subconsultant*(Number(p.markup)||0)/100,total=base+overhead+markup;return{rows,base,overhead,markup,total,retainer:total*(Number(p.retainer)||0)/100};}
  function prettyDate(value){if(!value)return"";return new Date(value+"T12:00:00").toLocaleDateString("en-US",{month:"long",day:"numeric",year:"numeric"})}
  function renderPreview(){const p=current();if(!p)return;const calc=calculate(p),notes=p.notes.split(/\n+/).map(value=>value.trim()).filter(Boolean),imageCard=(key,title,placeholder)=>`<div class="location-card">${p.images?.[key]?`<img src="${p.images[key]}" alt="${esc(title)}"><span>${esc(title)}</span>`:`<strong>${esc(title)}</strong>${esc(placeholder)}</div>`}</div>`;$("#proposalPaper").innerHTML=`<div class="pdf-top"><img class="pdf-logo" src="moment-engineering-logo.png" alt="Moment Engineering"><div class="pdf-contact">(714) 497-2623<br>info@momentengineering.us<br>RCE 92662 &nbsp;·&nbsp; <strong>Certified SBE / SLBE</strong></div></div><div class="pdf-rule"></div><div class="pdf-title"><h2>PROPOSAL</h2><span>FOR PROFESSIONAL SERVICES</span></div><div class="meta-grid"><div class="meta-cell"><b>Client</b><span>${esc(p.client||"—")}</span></div><div class="meta-cell"><b>Job no.</b><span>${esc(p.jobNumber||"—")}</span></div><div class="meta-cell"><b>Project address</b><span>${esc(p.address||"—")}</span></div><div class="meta-cell"><b>Date</b><span>${esc(prettyDate(p.proposalDate))}</span></div></div><div class="pdf-section-head">PROPOSED WORK + LOCATION</div><p class="scope-copy">${esc(p.scope)}</p><div class="location-strip">${imageCard("property","Property photo","Aerial view placeholder")}${imageCard("hazard","Hazard map","Parcel / geologic map")}${imageCard("sitePlan","Site plan","Attach when available")}</div><div class="pdf-section-head">COST BREAKDOWN</div><table class="cost-table"><thead><tr><th>Description of services</th><th>Hours</th><th>Rate</th><th>Fee</th></tr></thead><tbody>${calc.rows.map(row=>`<tr><td>${esc(row.description)}</td><td>${row.flat?"—":esc(row.hours)}</td><td>${row.flat?"Flat":money(row.rate)}</td><td>${money(row.fee)}</td></tr>`).join("")}</tbody></table><div class="totals"><div>Subtotal</div><div class="value">${money(calc.base)}</div><div class="label">Overhead &amp; administrative (${esc(p.overhead)}%)</div><div class="value">${money(calc.overhead)}</div><div class="label">Subconsultant markup (${esc(p.markup)}%)</div><div class="value">${money(calc.markup)}</div><div class="grand">TOTAL</div><div class="value grand">${money(calc.total)}</div></div><div class="pdf-section-head">NOTES</div><ul class="pdf-notes">${notes.map(note=>`<li>${esc(note)}</li>`).join("")}<li>A ${esc(p.retainer)}% retainer of ${money(calc.retainer)} is due prior to commencement; the balance is due upon delivery.</li></ul><div class="terms">Signature below authorizes Moment Engineering to proceed with the scope of services and fees described above. Terms and conditions are governed by the executed proposal.</div><div class="signature-row"><div class="signature">AUTHORIZED SIGNATURE</div><div class="signature">DATE</div></div><div class="pdf-footer"><span>MOMENT ENGINEERING &nbsp;·&nbsp; GEOTECHNICAL &amp; CIVIL ENGINEERING CONSULTANTS</span><span>PAGE 1 OF 1</span></div>`;}
  function renderEmpty(){$("#proposalPaper").innerHTML='<div style="display:grid;place-items:center;min-height:850px;color:#777;text-align:center"><div><h2>No eligible projects</h2><p>Add a project without a schedule or samples to begin.</p></div></div>'}
  function save(){if(!selectedId)return;localStorage.setItem(proposalKey,JSON.stringify(proposals));window.MomentWorkspaceCloud?.scheduleSave?.();$("#saveState").textContent="Saved";clearTimeout(saveTimer);saveTimer=setTimeout(()=>$("#saveState").textContent="Ready",1300)}
  function update(){const p=current();if(!p)return;["client","jobNumber","address","proposalDate","preparedBy","scope","notes"].forEach(key=>p[key]=$("#"+key).value);["overhead","markup","retainer"].forEach(key=>p[key]=Number($("#"+key).value)||0);renderPreview();$("#saveState").textContent="Saving…";clearTimeout(saveTimer);saveTimer=setTimeout(save,450)}
  $("#projectSelect").addEventListener("change",event=>showProject(event.target.value));document.querySelector(".editor-panel").addEventListener("input",event=>{const row=event.target.closest(".line-item");if(row){current().lines[Number(row.dataset.index)][event.target.dataset.key]=event.target.dataset.key==="description"?event.target.value:Number(event.target.value)||0;}update()});
  $("#lineItems").addEventListener("click",event=>{const index=event.target.dataset.remove;if(index===undefined)return;current().lines.splice(Number(index),1);renderLines();update()});$("#addLine").addEventListener("click",()=>{current().lines.push({id:uid(),description:"New service",hours:1,rate:0});renderLines();update()});
  function renderImageUploads(){const p=current();if(!p)return;p.images=p.images||{};Object.keys(placeholderImages).forEach(key=>{if(!p.images[key])p.images[key]=placeholderImages[key]});document.querySelectorAll("[data-image-slot]").forEach(card=>{const key=card.dataset.imageSlot,value=p.images[key],custom=value!==placeholderImages[key],preview=card.querySelector(".image-upload-preview"),remove=card.querySelector("[data-remove-image]");preview.innerHTML=custom?`<img src="${value}" alt="${esc(key)} preview">`:`<span>No image</span>`;remove.disabled=!custom})}
  function resizeImage(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(new Error("Image could not be read."));reader.onload=()=>{const image=new Image();image.onerror=()=>reject(new Error("Image format is not supported."));image.onload=()=>{const max=1400,scale=Math.min(1,max/Math.max(image.width,image.height)),canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(image.width*scale));canvas.height=Math.max(1,Math.round(image.height*scale));canvas.getContext("2d").drawImage(image,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL("image/jpeg",.86))};image.src=reader.result};reader.readAsDataURL(file)})}
  document.querySelector(".image-uploads").addEventListener("change",async event=>{const key=event.target.dataset.imageInput,file=event.target.files?.[0];if(!key||!file||!current())return;$("#saveState").textContent="Processing image…";try{current().images[key]=await resizeImage(file);renderImageUploads();renderPreview();save()}catch(error){$("#saveState").textContent=error.message}event.target.value=""});
  document.querySelector(".image-uploads").addEventListener("click",event=>{const key=event.target.dataset.removeImage;if(!key||!current())return;current().images[key]=placeholderImages[key];renderImageUploads();renderPreview();save()});
  function printPdf(){const previous=document.title,p=current();document.title=`Proposal_${(p?.jobNumber||"project").replace(/[^a-z0-9_-]+/gi,"_")}`;window.print();setTimeout(()=>document.title=previous,500)}
  $("#printProposal").addEventListener("click",printPdf);$("#downloadPdf").addEventListener("click",()=>{save();printPdf();const toast=$("#toast");toast.textContent="Choose ‘Save as PDF’ in the print window.";toast.classList.add("show");setTimeout(()=>toast.classList.remove("show"),3000)});
  load();
})();
