(()=>{
  const projectKey="boringLogAppState",calendarKey="moment-job-calendar-v1",accessKey="momentAccessControlV1";
  const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key)||"")||fallback}catch{return fallback}};
  const safe=value=>String(value??"").replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[char]);
  const projectState=read(projectKey,{projects:[]}),projects=Array.isArray(projectState.projects)?projectState.projects:[];
  let selectedId="",query="";
  const title=project=>project.name||project.address||project.number||"Untitled project";
  const team=()=>{const workers=read(accessKey,{}).workers||[];return workers.filter(person=>person?.id&&person.active!==false);};
  function renderProjects(){const visible=projects.filter(project=>[project.number,project.name,project.address,project.client].join(" ").toLowerCase().includes(query));document.querySelector("#projectCount").textContent=`${visible.length} available`;document.querySelector("#schedulerProjects").innerHTML=visible.length?visible.map(project=>`<button class="scheduler-project ${project.id===selectedId?"selected":""}" type="button" data-project="${safe(project.id)}"><span><strong>${safe(title(project))}</strong><span>${safe([project.number||"No project number",project.client||"No client"].join(" · "))}</span></span><small>Select</small></button>`).join(""):'<div class="empty">No projects match this search.</div>'}
  function renderTeam(){const people=team();document.querySelector("#schedulerTeam").innerHTML=people.length?people.map(person=>`<label class="team-option"><input type="checkbox" value="${safe(person.id)}"><span style="width:10px;height:10px;border-radius:50%;background:${safe(person.color||"#2f6f58")}"></span><span>${safe(person.name||"Worker")}</span></label>`).join(""):'<span class="empty">Add people in Admin to assign them here.</span>'}
  function selectProject(id){selectedId=id;const project=projects.find(item=>item.id===id);if(!project)return;document.querySelector("#selectedProjectName").textContent=title(project);document.querySelector("#selectedProjectMeta").textContent=[project.number||"No project number",project.client||"No client",project.address].filter(Boolean).join(" · ");document.querySelector("#schedulerClient").value=project.client||"";document.querySelector("#saveSchedule").disabled=false;document.querySelector("#scheduleStatus").textContent="";renderProjects()}
  function renderRecent(){const jobs=read(calendarKey,[]).filter(job=>job.date>=new Date().toISOString().slice(0,10)).sort((a,b)=>`${a.date} ${a.time||""}`.localeCompare(`${b.date} ${b.time||""}`)).slice(0,6);document.querySelector("#recentSchedules").innerHTML=jobs.length?jobs.map(job=>`<article class="recent-card"><strong>${safe(job.title)}</strong><span>${safe([job.date,job.time,job.jobNumber].filter(Boolean).join(" · "))}</span></article>`).join(""):'<div class="empty">No upcoming work is scheduled.</div>'}
  document.addEventListener("DOMContentLoaded",()=>{
    document.querySelector("#scheduleDate").value=new Date().toISOString().slice(0,10);renderProjects();renderTeam();renderRecent();
    document.querySelector("#projectSearch").addEventListener("input",event=>{query=event.target.value.trim().toLowerCase();renderProjects()});
    document.querySelector("#schedulerProjects").addEventListener("click",event=>{const button=event.target.closest("[data-project]");if(button)selectProject(button.dataset.project)});
    document.querySelector("#schedulerForm").addEventListener("submit",event=>{event.preventDefault();const project=projects.find(item=>item.id===selectedId);if(!project)return;const people=team(),assigneeIds=[...document.querySelectorAll("#schedulerTeam input:checked")].map(input=>input.value),assignees=assigneeIds.map(id=>people.find(person=>person.id===id)).filter(Boolean).map(person=>({id:person.id,name:person.name,email:person.email||"",color:person.color||"#2f6f58"}));const jobs=read(calendarKey,[]);jobs.push({id:crypto.randomUUID?.()||String(Date.now()),title:title(project),date:document.querySelector("#scheduleDate").value,time:document.querySelector("#scheduleTime").value,assigneeIds,assigneeId:assigneeIds[0]||"",assignees,jobNumber:project.number||"",type:"field",jobType:document.querySelector("#jobType").value,equipment:document.querySelector("#equipment").value,proposed:document.querySelector("#proposedWork").value.trim(),location:project.address||"",notes:document.querySelector("#scheduleNotes").value.trim(),sourceProjectId:project.id,parties:{client:{name:document.querySelector("#schedulerClient").value.trim(),email:document.querySelector("#schedulerEmail").value.trim()}}});localStorage.setItem(calendarKey,JSON.stringify(jobs));document.querySelector("#scheduleStatus").textContent="Scheduled and added to Calendar.";document.querySelector("#scheduleTime").value="";document.querySelector("#proposedWork").value="";document.querySelector("#scheduleNotes").value="";renderRecent()});
  });
})();
