(()=>{
  const projectKey="boringLogAppState",calendarKey="moment-job-calendar-v1",accessKey="momentAccessControlV1";
  const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key)||"")||fallback}catch{return fallback}};
  const safe=value=>String(value??"").replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[char]);
  const projectState=read(projectKey,{projects:[]}),projects=Array.isArray(projectState.projects)?projectState.projects:[];
  let selectedId="",query="";
  const title=project=>project.name||project.address||project.number||"Untitled project";
  const team=()=>{const workers=read(accessKey,{}).workers||[];return workers.filter(person=>person?.id&&person.active!==false);};
  function renderProjects(){const visible=projects.filter(project=>[project.number,project.name,project.address,project.client].join(" ").toLowerCase().includes(query));document.querySelector("#projectCount").textContent=`${visible.length} available`;document.querySelector("#schedulerProjects").innerHTML=visible.length?visible.map(project=>`<button class="scheduler-project ${project.id===selectedId?"selected":""}" type="button" data-project="${safe(project.id)}"><span><strong>${safe(title(project))}</strong><span>${safe([project.number||"No project number",project.client||"No client"].join(" · "))}</span></span><small>Select</small></button>`).join(""):'<div class="empty">No projects match this search.</div>'}
  function renderTeam(){const people=team();document.querySelector("#schedulerTeam").innerHTML=people.length?people.map(person=>`<label class="team-option"><input type="checkbox" value="${safe(person.id)}"><span style="width:10px;height:10px;border-radius:50%;background:${safe(person.color||"#2f6f58")}"></span><span>${safe(person.name||"Worker")}</span></label>`).join(""):'<span class="empty">Add people in Admin to assign them here.</span>'}
  function selectProject(id){selectedId=id;const project=projects.find(item=>item.id===id);if(!project)return;document.querySelector("#selectedProjectName").textContent=title(project);document.querySelector("#selectedProjectMeta").textContent=[project.number||"No project number",project.client||"No client",project.address].filter(Boolean).join(" · ");document.querySelector("#schedulerClient").value=project.client||"";document.querySelector("#saveSchedule").disabled=false;document.querySelector("#scheduleStatus").textContent="";renderProjects()}
  function renderRecent(){const jobs=read(calendarKey,[]).filter(job=>job.date>=new Date().toISOString().slice(0,10)).sort((a,b)=>`${a.date} ${a.time||""}`.localeCompare(`${b.date} ${b.time||""}`)).slice(0,6);document.querySelector("#recentSchedules").innerHTML=jobs.length?jobs.map(job=>`<article class="recent-card"><strong>${safe(job.title)}</strong><span>${safe([job.date,job.time,job.jobNumber].filter(Boolean).join(" · "))}</span></article>`).join(""):'<div class="empty">No upcoming work is scheduled.</div>'}
  function labeledValue(lines,labels){const pattern=labels.map(label=>label.replace(/[.*+?^${}()|[\]\\]/g,"\\$&").replace(/\s+/g,"\\s+")).join("|");for(let index=0;index<lines.length;index++){const match=lines[index].match(new RegExp(`^(?:${pattern})\\s*(?:[:#-]\\s*)?(.*)$`,"i"));if(!match)continue;if(match[1].trim())return match[1].trim();const next=lines[index+1]||"";if(next&&!new RegExp(`^(?:${pattern})\\b`,"i").test(next))return next.trim()}return""}
  function looksLikeAddress(value){return /\d{1,6}\s+.*\b(st|street|ave|avenue|rd|road|dr|drive|way|blvd|boulevard|lane|ln|ct|court|place|pl|circle|cir|terrace|ter|trail|trl|pkwy|parkway|hwy|highway)\b/i.test(value)||/\d{1,6}\s+.*,?\s+[^,]+,?\s+[A-Z]{2}\s*\d{5}?\b/i.test(value)}
  function cleanAddress(value){const cleaned=String(value||"").replace(/^(project address|site address|job location|project location|location|address)\s*[:#-]?\s*/i,"").replace(/\b(?:project|job)\s*(?:no\.?|number|#)?\s*[:#-]?\s*[A-Z0-9]{3,}[A-Z0-9-]*-\d{2,}\b/ig,"").replace(/\b[A-Z0-9]{3,}[A-Z0-9-]*-\d{2,}\b/g,"").trim(),parts=cleaned.split(/\s+(?:-|–|\|)\s+/).map(part=>part.trim()).filter(Boolean),address=parts.find(looksLikeAddress)||cleaned,street=address.match(/\d{1,6}\s+.+$/);return(street?street[0]:address).replace(/\s+/g," ").trim()}
  function cleanClientName(value){return String(value||"").replace(/\b(project|job|site|address|location|no\.?|number)\b/ig,"").replace(/\b[A-Z0-9]{3,}[A-Z0-9-]*-\d{2,}\b/ig,"").replace(/^[:#\-\s]+|[:#\-\s]+$/g,"").trim()}
  function parseProjectText(text){const normalized=String(text||"").replace(/\s+/g," ").trim(),jobNumber=normalized.match(/\(([A-Z0-9]{3,}[A-Z0-9-]*-\d{2,})\)/i)?.[1]||"",withoutJob=normalized.replace(/\([A-Z0-9]{3,}[A-Z0-9-]*-\d{2,}\)/ig,"").trim(),parts=withoutJob.split(/\s+(?:-|–|\u2013|\u2014)\s+/).map(part=>part.trim()).filter(Boolean),addressPart=parts.find(looksLikeAddress),namePart=parts.find(part=>part!==addressPart&&!looksLikeAddress(part));if(addressPart&&namePart)return{projectNumber:jobNumber,name:cleanClientName(namePart),address:cleanAddress(addressPart),client:cleanClientName(namePart)};const lines=String(text||"").split(/\r?\n/).map(line=>line.trim()).filter(Boolean),joined=lines.join(" "),projectNumber=labeledValue(lines,["Project No.","Project No","Project Number","Project #","Job No.","Job No","Job Number","Job #","Number"])||(joined.match(/\b[A-Z0-9]{3,}[A-Z0-9-]*-\d{2,}\b/i)?.[0]||""),name=labeledValue(lines,["Project Name","Project Title","Title","Name"]),addressLabel=labeledValue(lines,["Project Address","Site Address","Job Location","Project Location","Address"]),address=addressLabel&&looksLikeAddress(addressLabel)?cleanAddress(addressLabel):cleanAddress(lines.find(looksLikeAddress)||""),client=labeledValue(lines,["Client Name","Client","Contact Name","Contact","Customer Name","Customer","Owner Name","Owner","Homeowner","Prepared For","Bill To","Attention","Attn"]);return{projectNumber,name,address,client}}
  document.addEventListener("DOMContentLoaded",()=>{
    const manualDialog=document.querySelector("#manualProjectDialog"),manualForm=document.querySelector("#manualProjectForm"),manualError=document.querySelector("#manualProjectError");
    document.querySelector("#scheduleDate").value=new Date().toISOString().slice(0,10);renderProjects();renderTeam();renderRecent();
    document.querySelector("#addManualProject").addEventListener("click",()=>{manualForm.reset();manualError.textContent="";manualDialog.showModal()});
    ["#closeManualProject","#cancelManualProject"].forEach(selector=>document.querySelector(selector).addEventListener("click",()=>manualDialog.close()));
    document.querySelector("#autoFillSchedulerProject").addEventListener("click",()=>{const parsed=parseProjectText(document.querySelector("#schedulerProjectPaste").value);if(parsed.name)manualForm.elements.name.value=parsed.name;if(parsed.projectNumber)manualForm.elements.number.value=parsed.projectNumber;if(parsed.address)manualForm.elements.address.value=parsed.address;if(parsed.client)manualForm.elements.client.value=parsed.client;manualError.textContent=Object.values(parsed).some(Boolean)?"Project details filled. Review them, then save.":"No project details were recognized."});
    manualForm.addEventListener("submit",event=>{event.preventDefault();const values=Object.fromEntries(new FormData(manualForm)),name=values.name.trim(),number=values.number.trim(),address=values.address.trim(),client=values.client.trim();if(!name&&!number&&!address){manualError.textContent="Enter or paste a project name, number, or address.";return}const project={id:`manual-${Date.now()}`,name:name||address||number,number,address,client,source:"Manual"};projects.push(project);projectState.projects=projects;localStorage.setItem(projectKey,JSON.stringify(projectState));window.MomentWorkspaceCloud?.scheduleSave?.();query="";document.querySelector("#projectSearch").value="";renderProjects();selectProject(project.id);manualDialog.close()});
    document.querySelector("#projectSearch").addEventListener("input",event=>{query=event.target.value.trim().toLowerCase();renderProjects()});
    document.querySelector("#schedulerProjects").addEventListener("click",event=>{const button=event.target.closest("[data-project]");if(button)selectProject(button.dataset.project)});
    document.querySelector("#schedulerForm").addEventListener("submit",event=>{event.preventDefault();const project=projects.find(item=>item.id===selectedId);if(!project)return;const people=team(),assigneeIds=[...document.querySelectorAll("#schedulerTeam input:checked")].map(input=>input.value),assignees=assigneeIds.map(id=>people.find(person=>person.id===id)).filter(Boolean).map(person=>({id:person.id,name:person.name,email:person.email||"",color:person.color||"#2f6f58"}));const jobs=read(calendarKey,[]);jobs.push({id:crypto.randomUUID?.()||String(Date.now()),title:title(project),date:document.querySelector("#scheduleDate").value,time:document.querySelector("#scheduleTime").value,assigneeIds,assigneeId:assigneeIds[0]||"",assignees,jobNumber:project.number||"",type:"field",jobType:document.querySelector("#jobType").value,equipment:document.querySelector("#equipment").value,proposed:document.querySelector("#proposedWork").value.trim(),location:project.address||"",notes:document.querySelector("#scheduleNotes").value.trim(),sourceProjectId:project.id,parties:{client:{name:document.querySelector("#schedulerClient").value.trim(),email:document.querySelector("#schedulerEmail").value.trim()}}});localStorage.setItem(calendarKey,JSON.stringify(jobs));document.querySelector("#scheduleStatus").textContent="Scheduled and added to Calendar.";document.querySelector("#scheduleTime").value="";document.querySelector("#proposedWork").value="";document.querySelector("#scheduleNotes").value="";renderRecent()});
  });
})();
